version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./assets:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  redis:
    image: redis:latest

  server:
    build:
      dockerfile: Dockerfile
    command: python server.py
    volumes:
      - ./:/app
    depends_on:
      - redis


  worker:
    build:
      dockerfile: Dockerfile
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis